# Переменные и гипотезы


### Что такое _y_ {-}

1. ~~Грантов по годам на 10 000 исследователей (2014, 2015...2019)~~
2. ~~Грантов за период на 10 000 исследователей (два периода: 2014-2016, 2017-2019)~~
3. Доля грантов ~~по годам и~~ по двум периодам

_Примечание: оставляем 3. Нормируем не исследователями, а долей, чтобы не тратить потенциальный x_

### Что может обяснять _y_ {-}

И основные гипотези и контрольные переменные, пока всё в кучу.

*** 
**H1: Деньги к деньгам** -- если регион в период _t_ тратил деньги на науку, то в период _t+1_ у него будет больше грантов РНФ.

Возможные переменные:

1. Доля ВРП на R&D (период: 2013-2018) (источник: Росстат. Регоионы России) <span style="color: #ff66cc;">есть всё</span> 
2. Четрыре пепеменные по финансированию из фед бюджета (период: 2015-2019) (источник: форма наука-2) <span style="color: #ff66cc;">есть 2018</span>
    + на фундаментальный исследования
    + на прикладные исследования
    + другие гранты
    + другое финансирование

_Примечание: 2 в деньгах, в логарифмах?_

*** 
**H2: Человеческие ресурсы** -- если в регионе в период _t_ большое число публикаций, то в период _t+1_ у него будет больше грантов РНФ.

Возможные переменные:

1. Доля публикаций в Scopus (период: ?) (источник: Дашин датасет, надо города раскидать по регионам) <span style="color: #ff66cc;">уточнить</span> 
2. Число докторов наук (период: 2013-2018) (источник: Росстат. Регоионы России) <span style="color: #ff66cc;">есть всё</span> 
3. Число кандидатов наук (период: 2013-2018) (источник: Росстат. Регоионы России) <span style="color: #ff66cc;">есть всё</span> 

_Примечание: 2 и 3 нормировать на население?_

*** 
**H3: Инфрастуктура** -- если в регионе есть "особый университет" (5:100), в нем будет больше грантов РНФ.

Возможные переменные:

1. Дамми на унивеситет из 5:100 ([список тут](https://www.5top100.ru/universities/)) <span style="color: #ff66cc;">есть всё</span> 

_Примечание: скорее всего скореллированно с предыдущими переменными_

*** 
**H4: Гранты к грантам** -- если регион в период _t_ получил много грантов, то в период _t+1_ у него тоже будет много грантов РНФ.

Возможные переменные:

1. Доля региона в пероиод 2014-2016 (когда _у_ это доля региона в пероиод 2017-2019) <span style="color: #ff66cc;">есть</span> 

_Примечание: это что такое вообще? просто автокорреляция же? играем во веменные ряды на двух периодах? номрально ли это?_

*** 
**H5: Пространственный эффект** -- регион _i_ граничит с регионом _j_. В период _t_ регион _i_ получил много грантов, тогда в период _t+1_ регионом _j_ тоже получит много грантов. <span style="color: #ff66cc;">опровергнуто катрой</span> 

_Примечание: Для начала посмотреть карту? + [Индекс Морана](https://tsamsonov.github.io/r-geo-course/autocorrelation.html)?_

*** 
**H6: Диверсификация имеет значение** -- контроль на кол-во исследовательских организаций + чем регион преимущественно занимается. 

Возможные переменные:

1. Придумать дайверсити индекс для региона на основе данных РИНЦ (период:?) (источник: Дашин датасет) <span style="color: #ff66cc;">уточнить</span> 

*** 
**Заметки на полях**: Откуда эксперты, кто принимает решение? Есть ли регионе человек из экспертного совета?



